RestoBook/RestoBook/Controllers/AuthenticationController.cs
using Microsoft.AspNet.Identity;
using RestoBook.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Security.Claims;
using System.Security.Cryptography;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
//using RestoBook.Bean;
//using RestoBook.Entity;


namespace RestoBook.Controllers
{
    public class AuthenticationController : Controller
    {

        //    private static User mod = new User();
        //    private RestoBook.Entity.RoleProvider roleProvider = new RestoBook.Entity.RoleProvider();
        //    private DBContext db = new DBContext();
        //    // GET: Authentication
        //    public ActionResult Login()
        //    {
        //        return View();
        //    }

        //    [HttpPost]
        //    [AllowAnonymous]
        //    [ValidateAntiForgeryToken]
        //    public ActionResult Login(LoginViewModel model, string returnUrl)
        //    {
        //        ViewBag.ReturnUrl = returnUrl;

        //        if (!ModelState.IsValid)
        //        {
        //            return View(model);
        //        }
        //        if (!ValidateUser(model.Login, model.Password))
        //        {
        //            ModelState.AddModelError(string.Empty, "Le nom d'utilisateur ou le mot de passe est incorrect.");
        //            return View(model);
        //        }
        //        var loginClaim = new Claim(ClaimTypes.NameIdentifier, model.Login);
        //        var claimsIdentity = new ClaimsIdentity(new[] { loginClaim }, DefaultAuthenticationTypes.ApplicationCookie);
        //        var ctx = Request.GetOwinContext();
        //        var authenticationManager = ctx.Authentication;
        //        authenticationManager.SignIn(claimsIdentity);

        //        // Rediriger vers l'URL d'origine :
        //        if (Url.IsLocalUrl(ViewBag.ReturnUrl))
        //            return Redirect(ViewBag.ReturnUrl);
        //        // Par défaut, rediriger vers la page d'accueil :
        //        return RedirectToAction("Index", "Home");

        //    }
        //    private bool ValidateUser(string login, string password)
        //    {
        //        // TODO : insérer ici la validation des identifiant et mot de passe de l'utilisateur...

        //        // Pour ce tutoriel, j'utilise une validation extrêmement sécurisée...
        //        return login == password;
        //    }
        //    [HttpGet]
        //    public ActionResult Logout()
        //    {
        //        var ctx = Request.GetOwinContext();
        //        var authenticationManager = ctx.Authentication;
        //        authenticationManager.SignOut();

        //        // Rediriger vers la page d'accueil :
        //        return RedirectToAction("Index", "Home");
        //    }
        //    public User AjouterUtilisateur(string lastName, string firstName, string password, string email)
        //    {
        //        string passwordHash = HashPassword(password);
        //        User utilisateur = new User { FirstName = firstName, LastName = lastName, Email = email, Password = passwordHash };
        //        db.User.Add(utilisateur);
        //        db.SaveChanges();
        //        return utilisateur;
        //    }

        //    private string HashPassword(string password)
        //    {
        //        throw new NotImplementedException();
        //    }

        //    [HttpPost]
        //    public async Task<ActionResult> Register(RegisterModel utilisateur)
        //    {
        //        utilisateur.Password = getPasswordForUser();

        //        if (ModelState.IsValid)
        //        {
        //            string password = utilisateur.Password;
        //            User currentUser = GetCurrentUser();
        //            int currentUserRole = roleProvider.GetRoleForUser(currentUser);
        //            if (currentUserRole != 1)
        //            {
        //                return RedirectToAction("index", "home");
        //            }
        //            bool isExist = IsExistUser(utilisateur.Email);
        //            if (isExist == false)
        //            {
        //                ModelState.AddModelError("", "Adresse mail déjà utilisée");
        //                return View();
        //            }
        //            User user = AjouterUtilisateur(utilisateur.LastName, utilisateur.FirstName, utilisateur.Password, utilisateur.Email);

        //            //UserRole userRole = new UserRole();
        //            //userRole.IdUser = user.Id;
        //            //userRole.Roles = roleProvider.GetRoleById(2);
        //            //db.UserRole.Add(userRole);
        //            //db.SaveChanges();
        //            //var requete = from b in db.User
        //            //              where b.Email.Equals(utilisateur.Email)
        //            //              select b;
        //            //mod = requete.First();
        //            return RedirectToAction("InfoUtilisateur", new { password = password });

        //        }
        //        return View(utilisateur);
        //    }
        //    public User GetCurrentUser()
        //    {
        //        var currentUser = HttpContext.User.Identity.Name;

        //        var userRequete = from b in db.User
        //                          where b.Email.Equals(currentUser)
        //                          select b;
        //        return userRequete.FirstOrDefault();
        //    }
        //    public ActionResult Register()
        //    {
        //        return View();
        //    }
        //    public bool IsExistUser(string email)
        //    {

        //        User userToTest = db.User.FirstOrDefault(u => u.Email == email);
        //        if (userToTest == null)
        //        {
        //            return true;
        //        }
        //        return false;
        //    }
        //     public int GetRoleForUser()
        //    {
        //        var userid = HttpContext.User.Identity.GetUserId();

        //        var currentUser = from b in db.UserRole
        //                          where b.IdUser.Equals(userid)
        //                          select b.Roles;
        //        var resu = currentUser.FirstOrDefault<int>();

        //        if (resu != null)
        //        {
        //            return resu;
        //        }
        //        else
        //        {
        //            return 0;
        //        }
        //    }

        //    public string getPasswordForUser()
        //    {
        //        var chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
        //        var stringChars = new char[10];
        //        var random = new Random();

        //        for (int i = 0; i < stringChars.Length; i++)
        //        {
        //            stringChars[i] = chars[random.Next(chars.Length)];
        //        }

        //        return new String(stringChars);
        //    }

    }
}

RestoBook/RestoBook/Controllers/RestaurantController.cs
using RestoBook.Models;
using System.Collections.Generic;
using System.Web.Mvc;
using PagedList;
using RestoBook.DAL;
using RestoBook.Linq;
using RestoBook.Models.ViewModels;

namespace RestoBook.Controllers
{
    public class RestaurantController : Controller
    {
        public JsonResult AutoCompleteGetVille(string term)
        {
            LinqVille linqVille = new LinqVille();
            var result = linqVille.GetVilleByValue(term);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        // GET: Restaurant
        public ActionResult Proposer()
        {
            ViewModelAddRestaurant m_view = new ViewModelAddRestaurant();
            LinqCuisine linqCuisine = new LinqCuisine();
            m_view.ItemsCuisine = linqCuisine.GetAllCuisine();
            return View(m_view);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Proposer(ViewModelAddRestaurant model, bool EmptyVille)
        {
            LinqCuisine linqCuisine = new LinqCuisine();

            if (ModelState.IsValid)
            {
                Restaurants view_newRestaurant = model.m_restaurant;
                Ville view_ville = model.m_ville;
                Adresse view_addresse = model.m_adresse;
                Notation view_notation = model.m_notation;

                view_newRestaurant.lb_nom = System.Globalization.CultureInfo.CurrentCulture.TextInfo.ToTitleCase(view_newRestaurant.lb_nom);

                LinqRestaurant linqRestautant = new LinqRestaurant();

                int result = linqRestautant.ExistRestaurant(view_newRestaurant.lb_nom, view_addresse.lb_rue, view_addresse.lb_codepostal, view_ville.lb_ville);

                if (result>0)
                    return RedirectToAction("Index", "Home");

                LinqVille linqVille = new LinqVille();
                var existingCity = linqVille.GetVilleFirst(view_ville.lb_ville.ToLower());

                using(var db = new RestaurantDbContext())
                {
                    if ((EmptyVille) && existingCity == null)
                    {
                        view_ville.lb_ville = char.ToUpper(view_ville.lb_ville[0]) + view_ville.lb_ville.Substring(1);
                        view_addresse.lb_rue = view_addresse.lb_rue.Replace(",", "");
                        db.db_ville.Add(view_ville);
                        db.db_addresse.Add(view_addresse);
                    }
                    else
                    {
                        view_addresse.lb_rue = view_addresse.lb_rue.Replace(",", "");
                        db.db_ville.Attach(existingCity);
                        existingCity.Adresses.Add(view_addresse);
                    }

                    foreach (string typeCuisine in model.SelectedItemsCuisine)
                    {
                        TypeCuisine existingCuisine = linqCuisine.GetCuisineFirst(int.Parse(typeCuisine));
                        db.db_typecuisine.Attach(existingCuisine);
                        existingCuisine.Restaurants.Add(view_newRestaurant);
                    }

                    view_newRestaurant.Notations.Add(view_notation);

                    db.SaveChanges();
                }
                return RedirectToAction("Index", "Home");
            }

            model.ItemsCuisine = linqCuisine.GetAllCuisine();

            return View(model);
        }

        [ChildActionOnly]
        public ActionResult _Filter()
        {
            ViewModelFilter filter = new ViewModelFilter();
            LinqCuisine linqCuisine = new LinqCuisine();
            var result = linqCuisine.GetAllCuisine();
            List<ViewModelFilter> lstFilterCuisine = new List<ViewModelFilter>();
            foreach (var item in result)
            {
                lstFilterCuisine.Add(
                    new ViewModelFilter() { Checked = false, Id=item.Id_Cuisine,Value=item.lb_cuisne }
                );
            }
            return PartialView(lstFilterCuisine);
        }

        public ActionResult Lister(string search, string currentFilter, int? page)
        {
            LinqRestaurant linqRestaurant = new LinqRestaurant();

            int pageSize = 2;
            int pageNumber = (page ?? 1);

            if (TempData["Search"] != null && TempData["ResultSearch"] != null)
            {
                ViewBag.CurrentFilter = TempData["Search"];
                var result = (IEnumerable<ViewModelGroupRestaurants>)TempData["ResultSearch"];
                return View(result.ToPagedList(pageNumber, pageSize));
            }

            if (search != null)
            {
                page = 1;
            }
            else
            {
                search = currentFilter;
            }

            ViewBag.CurrentFilter = search;

            if (!string.IsNullOrEmpty(search))
            {
                var listerRestaurant = linqRestaurant.ListerRestaurants(search);
                var gpRestaurant = linqRestaurant.GroupRestaurant(listerRestaurant);
                return View(gpRestaurant.ToPagedList(pageNumber, pageSize));
            }

            return RedirectToAction("Index","Home");
        }

        //public ActionResult ListerRestaurantCuisine(int id,int? page)
        //{
        //    LinqRestaurant linqRestaurant = new LinqRestaurant();
        //    int pageSize = 2;
        //    int pageNumber = (page ?? 1);
        //    var lsrestaurantcuisine = linqRestaurant.ListerRestaurantByCuisine(id);
        //    var gpRestaurant = linqRestaurant.GroupRestaurant(lsrestaurantcuisine);
        //    return View(gpRestaurant.ToPagedList(pageNumber,pageSize));
        //}

        public ActionResult Details(int? id)
        {
            LinqRestaurant linqRestaurant = new LinqRestaurant();
            LinqNoteEvaluation linqEvaluation = new LinqNoteEvaluation();
            ViewModelDetailRestaurants model_details = new ViewModelDetailRestaurants();
            ViewModelAllDetailRestaurants model_Alldetails = new ViewModelAllDetailRestaurants();
            ViewModelEvaluation model_evaluation = new ViewModelEvaluation();

            if (TempData["RestaurantSearch"]!=null)
            {
                model_details = (ViewModelDetailRestaurants)TempData["RestaurantSearch"];
            }
            else
            {
                //model_details = linqRestaurant.DetailsRestaurantByList(id);
                model_details = linqRestaurant.DetailsRestaurantByList(id);

            }

            model_evaluation.nbDelicieux = linqEvaluation.getNbDelicieux(model_details.Id);
            model_evaluation.percentDelicieux = (model_evaluation.nbDelicieux * 100) / 1;

            model_evaluation.nbBon = linqEvaluation.getNbBon(model_details.Id);
            model_evaluation.percentBon = (model_evaluation.nbBon * 100) / 1;

            model_evaluation.nbAcceptable = linqEvaluation.getNbAcceptable(model_details.Id);
            model_evaluation.percentAcceptable = (model_evaluation.nbAcceptable * 100) / 1;

            model_evaluation.nbPassable = linqEvaluation.getNbPassable(model_details.Id);
            model_evaluation.percentPassable = (model_evaluation.nbPassable * 100) / 1;

            model_evaluation.nbMauvais = linqEvaluation.getNbPassable(model_details.Id);
            model_evaluation.percentMauvais = (model_evaluation.nbMauvais * 100) / 1;

            model_Alldetails.detailRestautants = model_details;
            model_Alldetails.evaluationlRestautants = model_evaluation;

            return View(model_Alldetails);
        }
    } 
}

RestoBook/RestoBook/Views/Shared/_Layout.cshtml
@using System.Security.Claims
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - RestoBook</title>              
    @Styles.Render("~/Content/Css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
</head>
<body>
    <div id="page">

        <div class="navbar navbar-inverse navbar-fixed-top" id="bgheader">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("RestoBook", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav navigation">
                        <li class="@(ViewBag.Title.Equals("Index") ? "active" : "" )">@Html.ActionLink("Home", "Index", "Home")</li>
                        <li class="@(ViewBag.Title.Equals("Tops") ? "active" : "" )">@Html.ActionLink("Tops", "", "")</li>
                        <li class="@(ViewBag.Title.Equals("Promotions") ? "active" : "" )">@Html.ActionLink("Promotions", "", "")</li>
                        <li class="@(ViewBag.Title.Equals("Evénements") ? "active" : "" )">@Html.ActionLink("Evénements", "", "")</li>
                        <li class="@(ViewBag.Title.Equals("Proposer") ? "active" : "" )">@Html.ActionLink("Proposer", "Proposer", "Restaurant")</li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right navigation" id="navLogin">
                        @if (Request.IsAuthenticated)
                        {
                            var claimIdentity = User.Identity as ClaimsIdentity;
                            var homeLinkText = "";
                            if (claimIdentity != null)
                            {
                                homeLinkText = "Bonjour, " + claimIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;
                            }
                            @Html.ActionLink(homeLinkText, "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                            <li>@Html.ActionLink("Se déconnecter", "Logout", "Authentication")</li>
                        }
                        else
                        {
                            <li>@Html.ActionLink("Sign in", "", "")</li>
                            <li>@Html.ActionLink("Login", "Login", "Authentication")</li>
                        }
                    </ul>
                </div>
            </div>
        </div>

        @RenderBody()
    </div>

        <footer class="footer">
            <div class="container">
                <p>&copy; @DateTime.Now.Year - RestoBook</p>
                <ul>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </footer>

    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("proposer", required: false)
    @RenderSection("lister", required: false)
    @RenderSection("details", required:false)
</body>
</html>

RestoBook/RestoBook/Views/Shared/_Search.cshtml
@using (Html.BeginForm("Search", "Home", FormMethod.Get))
{
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="input-group">
                @*@Html.TextBox("SearchString", ViewBag.CurrentFilter as string, new { @class = "form-control", placeholder = "Ville, rue, nom du restaurant", required = "required" })*@
                @Html.TextBox("SearchString", Model as string, new { @class = "form-control", placeholder = "Ville, rue, nom du restaurant", required = "required" })
                <span class="input-group-btn">
                    <button type="submit" class="btn btn-default">Recherche</button>
                </span>
            </div>
        </div>
    </div>
}

@Styles.Render("~/Content/Css/jqueryui")
@Scripts.Render("~/bundles/jqueryui")
@Scripts.Render("~/bundles/myautocomplete")

    